"""
JobHunter — Personalized Settings
==================================
HOW TO UPDATE THIS FILE:
1. Go to https://inseadjobhunter.netlify.app
2. Complete the Setup Wizard (or update Preferences)
3. Click "Download settings.py"
4. In this repo: click this file → Edit (pencil) → select all → paste → Commit

DO NOT edit this file manually — download a fresh one from the JobHunter website.
"""
import os

# ── YOUR PROFILE ──────────────────────────────────────────────────────────────
CANDIDATE_NAME = "INSEAD MBA Candidate"
ALERT_EMAIL    = "your@email.com"   # Email that receives the daily digest

# ── EMAIL CREDENTIALS (set via GitHub Secrets, not here) ─────────────────────
GMAIL_SENDER   = os.environ.get("GMAIL_SENDER", "")
GMAIL_APP_PASS = os.environ.get("GMAIL_APP_PASS", "")

# ── JOB SEARCH PREFERENCES ───────────────────────────────────────────────────
INDUSTRIES = [
    "Healthcare",
    "Medical Device",
    "Pharmaceutical",
]

GEOGRAPHIES = [
    "Singapore",
    "Hong Kong",
    "Taiwan",
]

ROLE_KEYWORDS = [
    "Digital Transformation",
    "AI Strategy",
    "Strategy Manager",
    "Business Development",
    "Management Consulting",
]

TARGET_COMPANIES = [
    "Roche",
    "Merck",
    "McKinsey",
    "Bain",
    "BCG",
]

SENIORITY_LEVELS = [
    "Senior Manager",
    "Director",
    "Manager",
]

# ── SCORING WEIGHTS (must sum to 1.0) ─────────────────────────────────────────
WEIGHT_INDUSTRY   = 0.30
WEIGHT_GEOGRAPHY  = 0.25
WEIGHT_ROLE       = 0.30
WEIGHT_COMPANY    = 0.15

# ── FILTER SETTINGS ───────────────────────────────────────────────────────────
MATCH_THRESHOLD    = 60    # Minimum score (0-100) to include in digest
MAX_JOBS_PER_EMAIL = 20    # Maximum jobs per email (hard cap: 30)

# ── SYSTEM SETTINGS (do not change) ──────────────────────────────────────────
CRON_SCHEDULE = "0 0 * * *"          # 00:00 UTC = 08:00 SGT
SEEN_JOBS_DB  = "data/seen_jobs.json"
